"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _foundation from "./foundation.bones.json";

configureBoneyard({
  color: "var(--skeleton)",
  darkColor: "var(--skeleton)",
  animate: "pulse",
});

registerBones({
  foundation: _foundation,
});
