import type { ApiRole } from "../../utils/constants.js";

/** Canonical capability keys (system/brain/roles-permissions.md); must match the frontend's `types/session.ts`. */
export const CAPABILITIES = [
  "directory.read",
  "profile.read.self",
  "profile.change.request",
  "employee.read",
  "employee.create",
  "employee.update",
  "attendance.capture.self",
  "attendance.read.self",
  "attendance.read.team",
  "attendance.regularize.request",
  "leave.request.self",
  "leave.cancel.self",
  "approval.decide",
  "payroll.prepare",
  "payroll.submit",
  "payroll.approve",
  "payroll.publish",
  "payment.export",
  "payslip.read.self",
  "document.upload",
  "document.read",
  "helpdesk.request.self",
  "helpdesk.queue",
  "expense.submit.self",
  "report.read",
  "engage.post",
  "letter.request.self",
  "loan.request.self",
  "tax.declare.self",
  "delegation.manage",
  "announcement.publish",
  "onboarding.manage",
  "policy.publish",
  "event.manage",
  "letter.issue",
  "loan.approve",
  "import.commit",
  "compensation.manage",
  "statutory.manage",
  "timesheet.submit.self",
  "timesheet.approve",
  "project.manage",
  "roster.manage",
  "exit.request.self",
  "settlement.prepare",
  "settlement.approve",
  "asset.read.self",
  "asset.manage",
  "performance.self",
  "performance.review",
  "performance.manage",
  "recruitment.manage",
  "candidate.interview",
  "survey.manage",
  "report.build",
  "access.manage",
  "audit.read",
] as const;

export type Capability = (typeof CAPABILITIES)[number];

/** Role → capability grants. Identical to the frontend mock's grants so both enforce the same rules. */
export const roleCapabilities: Record<ApiRole, readonly Capability[]> = {
  /** Every capability, organization-wide. Grant to as few people as possible; maker ≠ checker still applies. */
  super_admin: CAPABILITIES,
  employee: [
    "directory.read",
    "profile.read.self",
    "profile.change.request",
    "attendance.capture.self",
    "attendance.read.self",
    "attendance.regularize.request",
    "leave.request.self",
    "leave.cancel.self",
    "payslip.read.self",
    "document.upload",
    "document.read",
    "helpdesk.request.self",
    "expense.submit.self",
    "engage.post",
    "letter.request.self",
    "loan.request.self",
    "tax.declare.self",
    "timesheet.submit.self",
    "exit.request.self",
    "asset.read.self",
    "performance.self",
  ],
  manager: [
    "approval.decide",
    "attendance.read.team",
    "delegation.manage",
    "timesheet.approve",
    "roster.manage",
    "performance.review",
    "candidate.interview",
    "project.manage",
  ],
  hr_operator: [
    "employee.read",
    "employee.create",
    "employee.update",
    "approval.decide",
    "helpdesk.queue",
    "report.read",
    "announcement.publish",
    "onboarding.manage",
    "policy.publish",
    "event.manage",
    "letter.issue",
    "import.commit",
    "roster.manage",
    "project.manage",
    "settlement.prepare",
    "asset.manage",
    "performance.manage",
    "recruitment.manage",
    "survey.manage",
    "report.build",
    "access.manage",
    "audit.read",
  ],
  payroll_operator: [
    "payroll.prepare",
    "payroll.submit",
    "report.read",
    "compensation.manage",
    "statutory.manage",
    "settlement.prepare",
    "report.build",
  ],
  payroll_approver: [
    "payroll.approve",
    "payroll.publish",
    "payment.export",
    "report.read",
    "loan.approve",
    "statutory.manage",
    "settlement.approve",
    "report.build",
  ],
};

export function capabilitiesFor(roles: readonly ApiRole[]): Capability[] {
  return [...new Set(roles.flatMap((role) => roleCapabilities[role]))];
}
