"use client";

import {
  Add,
  Archive,
  ArrowDown2,
  ArrowLeft2,
  ArrowRight,
  ArrowRight2,
  ArrowSwapHorizontal,
  Award,
  Bank,
  Book1,
  Box1,
  BoxTick,
  Briefcase,
  Building,
  Buildings2,
  Calculator,
  Calendar1,
  CalendarTick,
  Call,
  Card,
  Category,
  Chart2,
  ClipboardText,
  ClipboardTick,
  Clock,
  CloseCircle,
  ColorSwatch,
  Crown1,
  Cup,
  Danger,
  Diagram,
  DocumentDownload,
  DocumentText,
  DocumentUpload,
  Edit2,
  EmojiHappy,
  ExportCurve,
  ExportSquare,
  Eye,
  Filter,
  Flag,
  FolderOpen,
  Gift,
  Global,
  Graph,
  Heart,
  Home2,
  ImportCurve,
  InfoCircle,
  Kanban,
  Key,
  Layer,
  Level,
  Like1,
  Location,
  Lock,
  Login,
  LogoutCurve,
  MedalStar,
  Menu,
  MessageQuestion,
  Messages2,
  MoneyRecive,
  MoneySend,
  Monitor,
  Moon,
  Note1,
  Notification,
  People,
  PercentageSquare,
  PresentionChart,
  Printer,
  Profile2User,
  Ranking,
  Receipt2,
  ReceiptText,
  Refresh,
  RepeatCircle,
  SearchNormal1,
  SecurityUser,
  Send2,
  Setting2,
  Share,
  ShieldTick,
  SidebarLeft,
  Sms,
  Speaker,
  Star1,
  StatusUp,
  Sun1,
  Task,
  TaskSquare,
  Text,
  TickCircle,
  Timer1,
  Translate,
  Trash,
  TrendUp,
  User,
  UserAdd,
  UserRemove,
  UserSearch,
  UserTick,
  Wallet2,
  WalletMoney,
  Warning2,
  Whatsapp,
} from "iconsax-reactjs";

/** Semantic vocabulary → verified Iconsax exports (reusable-components.md). */
const icons = {
  add: Add,
  approvals: TaskSquare,
  archive: Archive,
  arrow: ArrowRight,
  attendance: Clock,
  award: Award,
  back: ArrowLeft2,
  bank: Bank,
  book: Book1,
  box: Box1,
  boxTick: BoxTick,
  briefcase: Briefcase,
  building: Building,
  buildings: Buildings2,
  calculator: Calculator,
  calendar: Calendar1,
  calendarCheck: CalendarTick,
  card: Card,
  chart: Chart2,
  check: TickCircle,
  chevron: ArrowDown2,
  chevronRight: ArrowRight2,
  clipboard: ClipboardText,
  clipboardTick: ClipboardTick,
  close: CloseCircle,
  crown: Crown1,
  cup: Cup,
  danger: Danger,
  diagram: Diagram,
  document: DocumentText,
  documents: FolderOpen,
  download: DocumentDownload,
  edit: Edit2,
  expenses: Receipt2,
  exportCurve: ExportCurve,
  external: ExportSquare,
  eye: Eye,
  filter: Filter,
  flag: Flag,
  gift: Gift,
  globe: Global,
  graph: Graph,
  grid: Category,
  heart: Heart,
  helpdesk: MessageQuestion,
  home: Home2,
  importCurve: ImportCurve,
  info: InfoCircle,
  kanban: Kanban,
  key: Key,
  layers: Layer,
  level: Level,
  like: Like1,
  location: Location,
  lock: Lock,
  login: Login,
  logout: LogoutCurve,
  mail: Sms,
  medal: MedalStar,
  megaphone: Speaker,
  menu: Menu,
  messages: Messages2,
  moneyIn: MoneyRecive,
  moneyOut: MoneySend,
  monitor: Monitor,
  moon: Moon,
  note: Note1,
  notification: Notification,
  palette: ColorSwatch,
  payroll: WalletMoney,
  payslip: ReceiptText,
  people: People,
  percent: PercentageSquare,
  phone: Call,
  plus: Add,
  presentation: PresentionChart,
  printer: Printer,
  profile: User,
  ranking: Ranking,
  refresh: Refresh,
  repeat: RepeatCircle,
  search: SearchNormal1,
  security: SecurityUser,
  send: Send2,
  settings: Setting2,
  share: Share,
  shield: ShieldTick,
  sidebar: SidebarLeft,
  smile: EmojiHappy,
  star: Star1,
  status: StatusUp,
  sun: Sun1,
  swap: ArrowSwapHorizontal,
  task: Task,
  team: Profile2User,
  text: Text,
  timer: Timer1,
  translate: Translate,
  trash: Trash,
  trend: TrendUp,
  upload: DocumentUpload,
  userAdd: UserAdd,
  userRemove: UserRemove,
  userSearch: UserSearch,
  userTick: UserTick,
  wallet: Wallet2,
  warning: Warning2,
  whatsapp: Whatsapp,
};
export type IconName = keyof typeof icons;
interface AppIconProps {
  name: IconName;
  size?: 16 | 20 | 24 | 32;
  label?: string;
  variant?: "Linear" | "Bold" | "Bulk";
  className?: string;
}

export function AppIcon({ name, size = 20, label, variant = "Linear", className }: AppIconProps) {
  const Icon = icons[name];
  return (
    <span
      className={className ? `app-icon ${className}` : "app-icon"}
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
    >
      <Icon size={size} color="currentColor" variant={variant} aria-hidden="true" />
    </span>
  );
}
